services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: "1"
      REDIS_HOST: "redis"
    depends_on:
      - redis
    volumes:
      - .env:/app/.env
      - ./:/app
    command: ["uv", "run", "uvicorn", "poc_valves.api:create_app", "--host", "0.0.0.0", "--port", "8000"]

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api
