from __future__ import annotations
from typing import Optional
from pydantic import BaseModel, Field


class SV2OutputModel(BaseModel):
    tag_no: Optional[str] = Field(None, description="Tag No. (Row 1)")
    service: Optional[str] = Field(None, description="Service (Row 2)")
    fluid_name: Optional[str] = Field(None, description="Process Fluid (Row 14)")
    fluid_phase: Optional[str] = Field(None, description="Upstream Condition (Row 15)")
    inlet_pipe_size_sch: Optional[str] = Field(None, description="Line Size and Schedule — Inlet (Row 11)")
    outlet_pipe_size_sch: Optional[str] = Field(None, description="Line Size and Schedule — Outlet (Row 11)")
    design_pressure_max: Optional[str] = Field(None, description="Design Pressure / Temperature (Row 27)")
    design_pressure_min: Optional[str] = Field(None, description="Design Pressure / Temperature (Row 27)")
    design_temp_max: Optional[str] = Field(None, description="Design Pressure / Temperature (Row 27)")
    design_temp_min_mdmt: Optional[str] = Field(None, description="Ambient Temperature (Row 5) / Process Notes Page 2")
    flow_rate_max: Optional[str] = Field(None, description="Flow Rate @ Max Flow (Row 18)")
    flow_rate_nor: Optional[str] = Field(None, description="Flow Rate @ Norm Flow (Row 18)")
    flow_rate_min: Optional[str] = Field(None, description="Flow Rate @ Min Flow (Row 18)")
    inlet_pressure_max: Optional[str] = Field(None, description="Inlet Pressure @ Max Flow (Row 19)")
    inlet_pressure_nor: Optional[str] = Field(None, description="Inlet Pressure @ Norm Flow (Row 19)")
    inlet_pressure_min: Optional[str] = Field(None, description="Inlet Pressure @ Min Flow (Row 19)")
    outlet_pressure_max: Optional[str] = Field(None, description="Not directly stated — derived from Rows 19 & 20")
    outlet_pressure_nor: Optional[str] = Field(None, description="Not directly stated — derived from Rows 19 & 20")
    outlet_pressure_min: Optional[str] = Field(None, description="Not directly stated — derived from Rows 19 & 20")
    pressure_drop_max: Optional[str] = Field(None, description="Pressure Drop @ Max Flow (Row 20)")
    pressure_drop_nor: Optional[str] = Field(None, description="Pressure Drop @ Norm Flow (Row 20)")
    pressure_drop_min: Optional[str] = Field(None, description="Pressure Drop @ Min Flow (Row 20)")
    temperature_max: Optional[str] = Field(None, description="Inlet Temperature @ Max Flow (Row 21)")
    temperature_nor: Optional[str] = Field(None, description="Inlet Temperature @ Norm Flow (Row 21)")
    temperature_min: Optional[str] = Field(None, description="Inlet Temperature @ Min Flow (Row 21)")
    specific_gravity_molecular_weight: Optional[str] = Field(None, description="Inlet Density / Specific Gravity / Molecular Mass (Row 22)")
    viscosity: Optional[str] = Field(None, description="Inlet Viscosity (Row 24)")
    compressibility_factor_z: Optional[str] = Field(None, description="Inlet Compressibility Factor (Row 23)")
    specific_heats_ratio_k: Optional[str] = Field(None, description="Inlet Specific Heats Ratio (Row 25)")
    vapour_pressure: Optional[str] = Field(None, description="Inlet Vapour Pressure (Row 26)")
    valve_type: Optional[str] = Field(None, description="Body Type (Row 32)")
    body_material: Optional[str] = Field(None, description="Body Material (Row 36)")
    bonnet_type: Optional[str] = Field(None, description="Bonnet Type / Material (Row 37)")
    flow_direction: Optional[str] = Field(None, description="Flow Direction (Row 38)")
    end_connection_rating: Optional[str] = Field(None, description="End Connec. & Rating (Row 35)")
    flow_characteristic: Optional[str] = Field(None, description="Characteristic (Rated Cv / Characteristic Row 34)")
    trim_plug_type: Optional[str] = Field(None, description="Trim Type (Row 42)")
    plug_material: Optional[str] = Field(None, description="Plug / Ball / Disk Material (Row 44)")
    seat_material: Optional[str] = Field(None, description="Seat Material (Row 45)")
    seat_leakage_class: Optional[str] = Field(None, description="Tightness Requirements (Row 7)")
    guiding: Optional[str] = Field(None, description="Guiding / No. of Ports (Row 41)")
    actuator_type: Optional[str] = Field(None, description="Type (Actuator) (Row 50)")
    actuator_action_air_failure: Optional[str] = Field(None, description="Power Failure Position (Row 9) + Air Failure Valve (Row 52)")
    supply_pressure: Optional[str] = Field(None, description="Available Air Supply Pressure (Row 8)")
    bench_range: Optional[str] = Field(None, description="Bench Range (Row 54)")
    shut_off_pressure: Optional[str] = Field(None, description="Actuator Design Pressure (Row 10)")
    handwheel: Optional[str] = Field(None, description="Handwheel (Row 53)")
    positioner_type: Optional[str] = Field(None, description="Not stated in Enquiry DS (Row 56 = VTA/VTA)")
    positioner_make: Optional[str] = Field(None, description="Positioner MFR (Row 56)")
    positioner_model: Optional[str] = Field(None, description="Positioner Model (Row 56)")
    positioner_protocol_casing: Optional[str] = Field(None, description="Signal Inlet (Row 57)")
    positioner_action_input_signal: Optional[str] = Field(None, description="Signal Inlet (Row 57) + Increase Signal Valve (Row 58)")
    positioner_certification: Optional[str] = Field(None, description="Area Classification (Row 4)")
    position_transmitter: Optional[str] = Field(None, description="Position Transmitter (Row 61)")
    airset_make_model_qty: Optional[str] = Field(None, description="Air Set MFR / Model (Row 72)")
    airset_set_pressure_filter: Optional[str] = Field(None, description="Airset Set Pressure (Row 73) / Filter (Row 74)")
    painting_scheme: Optional[str] = Field(None, description="Not in standard Enquiry DS body — from PO/project")
    actuator_colour: Optional[str] = Field(None, description="Power Failure Position (Row 9)")
    cable_gland_type: Optional[str] = Field(None, description="Not in Enquiry DS")
    cable_gland_certification: Optional[str] = Field(None, description="Area Classification (Row 4)")
    ibr_applicability: Optional[str] = Field(None, description="Process Fluid (Row 14/15) + Specification Notes (DS Page 2)")
    ndt_rt_extent: Optional[str] = Field(None, description="Not in Enquiry DS directly — standard requirement")
    ndt_pmi_test: Optional[str] = Field(None, description="Not in Enquiry DS directly — standard requirement")
    ndt_igc_test: Optional[str] = Field(None, description="Trim/Seat Material (Rows 44/45) — triggered by Austenitic SS")
    valve_operating_signature: Optional[str] = Field(None, description="Not in Enquiry DS — standard requirement")
    peso_certificate: Optional[str] = Field(None, description="Area Classification (Row 4)")

